version: '3.4'

services:
  stolibot:
    image: stolibot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
      - ./discord.env
      - ./notion.env
